## filename = AGEPRO_Input_Det.R
#' A function for creating an AGEPRO input file with Deterministic recruitment
#'
#' Uses output from SS to draft an input file, functionality is still limited
#' (i.e. no time-varying, not all recruitment models, etc.)
#' @param output.dir this is where you want the finished input file to be written
#' @param boot_file bootstrap file path location
#' @param NBoot Number of bootstrap replicates of initial population numbers at age (# of rows in bootfile)
#' @param BootFac Units of population numbers in boot_file, e.g. BootFac=1000 sets units of numbers at age to be 1000 fish
#' @param SS_Out output list generated by SS_to_Agepro
#' @param ModelName Name of the projection model
#' @param ProjStart The start year of the projections
#' @param NYears The number of years in the projection
#' @param MinAge the minimum age of fish in the projection (usually 1, note that is other than 1, the output generated by SS_to_Agepro will not work with this code)
#' @param NSims Number of simulations in the projection
#' @param NRecr_models Number of recruitment models to be used, note that only 1 recruitment model is supported by this code at this time
#' @param Discards whether or not your model includes discards (0 = No, 1 = Yes)
#' @param set.seed random number to set seed
#' @param ScaleFactor Scaling factor for output units of [1] Biomass, [2] Recruits, and [3] Stock numbers
#' @param For example, ScaleFactor = c(1000,1000,1000) set biomass units to be 1000 kg, and recruits and numbers to be 1000 fish
#' @param UserSpecified vector of length 7 indicating if the data will be user specified (0), read from a file (1), or set the same as the Jan-1 data (-1) when applicable for: [1] January-1 WAA, [2] SSB WAA, [3] Mid-Year WAA, [4] Catch WAA, [5] Natural Mortality, [6] Maturity and [7] Fishery Selectivity 
#' @param TimeVary  vector of length 7 indicating if the data will be not time varying (0) or time-varying (1) for: [1] January-1 WAA, [2] SSB WAA, [3] Mid-Year WAA, [4] Catch WAA, [5] Natural Mortality, [6] Maturity and [7] Fishery Selectivity (Note this code does not support time-varying data)
#' @param FemaleFrac Fraction of females in the population at maturity
#' @param Recruitment List containing the Recruitment model option number, the vector of probabilities (in this case all ones because we don't support more than one recruitment model), and the additional info needed for the respective recruitment model. See the descriptions in 013_BuildAGEPROinputfile.R for guidance on the recruitment input
#' @param Harvest The input data for the harvest settings, it would be a list with two items: Harvest type (1 = catch/landings, 0 = Fishing mortality, 2 = Removals) for each projection year, and a matrix of the values with each column corresponding to a year and each row a fleet
#' @param doRebuild TRUE or FALSE to do the rebuilding program
#' @param RebuildTargetSSB (optional) The target biomass for a rebuilding program
#' @param RebuildTargetYear (optional) the target year for a rebuilding program
#' @param PercentConfidence (optional) the percentile at which the rebuilding program meets its goal
#' @param LandingType (optional) Rebuilding biomass target type (SSB = 0, Jan-1 = 1, or Mid-Year = 2)
#' @param ThresholdReport TRUE or FALSE to create the Reference Point threshold report
#' @param RefPointSSB (optional) Threshold report Spawning stock biomass (in mt) reference point
#' @param RefPointJan1 (optional) Threshold report January-1 biomass (in mt) reference point
#' @param RefPointMidYr (optional) Threshold report Mean Biomass (in mt) reference point
#' @param RefPointF (optional) Threshold report F reference point
#' @param SetBounds TRUE or FALSE to set maximum weight and natural mortality bounds
#' @param MaxWeight (optional) maximum weight bound (in kg)
#' @param MaxNatM (optional) maximum natural mortality bound
#' @param SumReport create a summary report of stock numbers at age (1 = yes, 0 = no)
#' @param AuxFiles create Auxiliary stochastic data files (1 = yes, 0 = no) 
#' @param RExport export results to R (1 = yes, 0 = no)
#' @param SetScale TRUE or FALSE specify scale factors for output report file, uses values specified in ScaleFactor
#' @param PercentileReport TRUE or FALSE Request percentile report
#' @param Percentile (optional) Report percentile
#' 
#' @return writes a text file (.inp) in the output.dir with the structure ModelName.inp
#' @author Michelle Sculley
## Updated by Jon Brodziak 2-28-2024


AGEPRO_INP<-function(output.dir = "",
                    boot_file = "",
					NBoot = 100,
					BootFac = 1000,
                    SS_Out = SSInput,
                    ModelName="Test1",
                    ProjStart = 2021,
                    NYears = 10,
                    MinAge = 1,
                    NSims = 10000,
                    NRecr_models = 1,
                    Discards = 0,
                    set.seed = 123,
                    ScaleFactor = c(1000,1000,1000),  #Output scaling factors for biomass, recruits and stock numbers
                    UserSpecified = c(0,0,0,0,0,0,0),
                    TimeVary = c(0,0,0,0,0,0,0),
                    FemaleFrac=0.5,
                    Recruitment=Recruitment,
                    Harvest=Harvest,
                    doRebuild=FALSE,
                    RebuildTargetSSB = NULL,
                    RebuildTargetYear = NULL,
                    PercentConfidence = NULL,
                    LandingType = 1,
                    ThresholdReport = FALSE,
                    RefPointSSB = NULL,
                    RefPointJan1 = NULL,
                    RefPointMidYr = NULL,
                    RefPointF = NULL,
                    SetBounds = TRUE,
                    MaxWeight = 150,
                    MaxNatM = 1,
                    SumReport = 1,
                    AuxFiles = 0,
                    RExport = 0,
                    SetScale = TRUE,
                    PercentileReport = TRUE,
                    Percentile = 50
                    
                    
                        
){

  Jan_WAA <- SS_Out$Jan_WAA
  Jan_WAACV <- SS_Out$Jan_WAACV
  SSB_WAA <-SS_Out$SSB_WAA
  SSB_WAACV <-SS_Out$SSB_WAACV
  MidYr_WAA <- SS_Out$MidYr_WAA
  MidYr_WAACV <- SS_Out$MidYr_WAACV
  Catch_WAA <- SS_Out$Catage
  Catch_WAACV <- SS_Out$CatageCV
  MaxAge <- SS_Out$MaxAge
  Nfleets <- SS_Out$Nfleets
  MatAtAge <- SS_Out$MatAtAge
  MatAtAgeCV <- SS_Out$MatAtAgeCV
  Fishery_SelAtAge <- SS_Out$Fishery_SelAtAge
  Fishery_SelAtAgeCV <- SS_Out$Fishery_SelAtAgeCV
  NatMort_atAge <-  SS_Out$NatMort_atAge
  NatMort_atAgeCV <-  SS_Out$NatMort_atAgeCV
  
  
  # Check if the directory exists
  if (!dir.exists(output.dir)) {
    # If it doesn't exist, create a new directory
    dir.create(output.dir, recursive = TRUE)
    message("The output directory ", output.dir, " has been created.\n")
  } else {
    message("The output directory ", output.dir, " already exists.\n")
  }
  
  
 GENERAL <- c(ProjStart, ProjStart + (NYears-1), MinAge, MaxAge, NSims, Nfleets, NRecr_models, Discards, set.seed)

  
  # Create a list of strings to be pasted
  lines <- list(
    "AGEPRO VERSION 4.0",
    "[CASEID]",
    ModelName,
    "[GENERAL]",
    paste(GENERAL, collapse = "  "),
    "[BOOTSTRAP]",
    paste(c(NBoot, BootFac), collapse = "  "),
    boot_file,
    "[STOCK_WEIGHT]",
    paste(c(UserSpecified[1], TimeVary[1]), collapse = "  "))
  
  if (TimeVary[1] == 1) {
    "This function can't be used for time-varying WAA yet, please input manually in the AGEPRO gui."
  } else {
    if (UserSpecified[1] == 0) {
      lines$Jan_WAA1<-paste(Jan_WAA, collapse = "  ")
      lines$Jan_WAA2<-paste(Jan_WAACV, collapse = "  ")
    }
  }
  lines$SSBWeight<-"[SSB_WEIGHT]"
  lines$SSBWeight2<-paste(c(UserSpecified[2], TimeVary[2]), collapse = "  ")
  
  if (TimeVary[2] == 1) {
    "This function can't be used for time-varying WAA yet, please input manually in the AGEPRO gui."
  } else {
    if (UserSpecified[2] == 0) {
      lines$SSBWeight3<-paste(SSB_WAA, collapse = "  ")
      lines$SSBWeight4<-paste( SSB_WAACV, collapse = "  ")
    }
  }
  lines$MeanWeight<-"[MEAN_WEIGHT]"
  lines$MeanWeight2<-paste(c(UserSpecified[3], TimeVary[3]), collapse = "  ")
  if (TimeVary[3] == 1) {
    "This function can't be used for time-varying WAA yet, please input manually in the AGEPRO gui."
  } else {
    if (UserSpecified[3] == 0) {
      lines$MeanWeight3<-paste(MidYr_WAA, collapse = "  ")
      lines$MeanWeight4<-paste(MidYr_WAACV, collapse = "  ")
    }
  }
  lines$CatchWeight<-"[CATCH_WEIGHT]"
  lines$CatchWeight2<-paste(c(UserSpecified[4], TimeVary[4]), collapse = "  ")
  if (TimeVary[4] == 1) {
    "This function can't be used for time-varying WAA yet, please input manually in the AGEPRO gui."
  } else {
    if (UserSpecified[4] == 0) {
      for (i in 1:Nfleets){lines[[paste0("CatchWeight",i+2)]]<-paste(Catch_WAA[i,-1], collapse = "  ")}
      for (i in 1:Nfleets){lines[[paste0("CatchWeight",i+Nfleets+3)]]<-paste(Catch_WAACV[i,], collapse = "  ")}
    }
  }
  
  ## Natural mortality
  lines$NatMort<-"[NATMORT]"
  lines$NatMort2<-paste(c(UserSpecified[5], TimeVary[5]), collapse = "  ")
  lines$NatMort3<-paste(unlist(NatMort_atAge), collapse = "  ")
  lines$NatMort4<-paste(unlist(NatMort_atAgeCV), collapse = "  ")
  
  lines$Bio<-"[BIOLOGICAL]"
  lines$Bio2<-paste(c(0))
  lines$Bio3<-paste(c(FemaleFrac))
  lines$Bio4<-paste(c(1 - FemaleFrac))
  
  lines$Mat<-"[MATURITY]"
  lines$Mat2<-paste(c(UserSpecified[6], TimeVary[6]), collapse = "  ")
  lines$Mat3<-paste(unlist(MatAtAge), collapse = "  ")
  lines$Mat4<-paste(unlist(MatAtAgeCV), collapse = "  ")
  
  ##Fishery selectivity at age
  lines$FishSel<-"[FISHERY]"
  lines$FishSel2<-paste(c(UserSpecified[7], TimeVary[7]), collapse = "  ")
  for(i in 1:Nfleets) {lines[[paste0("FishSel",i+2)]]<-paste(Fishery_SelAtAge[i,-1], collapse="  ")}
  for (i in 1:Nfleets){ lines[[paste0("FishSel",i+3+Nfleets)]]<-paste(Fishery_SelAtAgeCV[i,], collapse="  ")}
  
  lines$recr<-"[RECRUIT]"
  lines$recr2<-paste(c(Recruitment$RecFac, Recruitment$SSBFac, Recruitment$MaxRecObs), collapse = "  ")
  lines$recr3<-paste(Recruitment$Recr_Model)
  for (i in 1:NYears){ lines[[paste0("recr",i+3)]]<-paste(Recruitment$Recr_Prob[i])}
   
  if (Recruitment$Recr_Model %in% c(1, 4, 9, 15)) {
    "Recruitment model not supported."
  }
  if (Recruitment$Recr_Model %in% c(2)) {
    lines$Rmod1<-paste(Recruitment$Nobs)
    lines$Rmod2<-paste(Recruitment$Recruits$pred_recr, collapse = "  ")
    lines$Rmod3<-paste(Recruitment$Recruits$SpawnBio, collapse = "  ")
  }
  if (Recruitment$Recr_Model %in% c(3)) {
    lines$Rmod1<-paste(Recruitment$Nobs)
    lines$Rmod2<-paste(Recruitment$Recruits, collapse = "  ")
  }
  if (Recruitment$Recr_Model %in% c(5, 6, 10, 11)) {
    lines$Rmod1<-paste(Recruitment$alpha, Recruitment$beta, Recruitment$var, collapse = "  ")
    if (Recruitment$Recr_Model %in% c(10, 11)) {
      lines$Rmod2<-paste(Recruitment$Phi, Recruitment$LastResid, collapse = "  ")
    }
  }
  if (Recruitment$Recr_Model %in% c(7, 12)) {
    lines$Rmod1<-paste(Recruitment$alpha, Recruitment$beta, Recruitment$Kparm, Recruitment$var, collapse = "  ")
    if (Recruitment$Recr_Model == 12) {
      lines$Rmod2<-paste(Recruitment$Phi, Recruitment$LastResid, collapse = "  ")
    }
  }
  if (Recruitment$Recr_Model %in% c(8, 13)) {
    lines$Rmod1<-paste(Recruitment$mean, Recruitment$stdev, collapse = "  ")
    if (Recruitment$Recr_Model == 13) {
      lines$Rmod2<-paste(Recruitment$Phi, Recruitment$LastResid, collapse = "  ")
    }
  }
  if (Recruitment$Recr_Model == 14) {
    lines$Rmod1<-paste(Recruitment$Nobs)
    lines$Rmod2<-paste(Recruitment$Recruits$pred_recr, collapse = "  ")
  }
  if (Recruitment$Recr_Model %in% c(16, 17, 18, 19)) {
    lines$Rmod1<-paste(Recruitment$Ncoeff, Recruitment$var, Recruitment$Intercept, collapse = "  ")
    lines$Rmod2<-paste(Recruitment$Coeff, collapse = "  ")
    lines$Rmod3<-paste(Recruitment$Observations, collapse = "  ")
  }
  if (Recruitment$Recr_Model == 20) {
    lines$Rmod1<-paste(Recruitment$Data, collapse = "  ")
  }
  if (Recruitment$Recr_Model == 21) {
    lines$Rmod1<-paste(Recruitment$Nobs)
    lines$Rmod2<-paste(Recruitment$Obs, collapse = "  ")
    lines$Rmod3<-paste(Recruitment$SSBHingeValue, collapse = "  ")
  }
  
  
  ##read in harvest data
  lines$harvest<-"[HARVEST]"
  lines$harves2<-paste(Harvest$Type, collapse="  ")
  for (i in 1:Nfleets) {lines[[paste0("harvest",i+2)]]<-paste(Harvest$Harvest[i,], collapse="  ")}
  
  if (doRebuild == TRUE) {
    lines$rebuild<-"[REBUILD]"
    lines$rebuild2<-paste(c(RebuildTargetYear, RebuildTargetSSB, PercentConfidence, LandingType), collapse = "  ")
  }
  
  
  if (ThresholdReport == TRUE) {
    lines$thresh<-"[REFPOINT]"
    lines$thresh2<-paste(c(RefPointSSB, RefPointJan1, RefPointMidYr, RefPointF), collapse = "  ")
  }
  
  
  if (SetBounds == TRUE) {
    lines$bounds<-"[BOUNDS]"
    lines$bounds2<-paste(c(MaxWeight, MaxNatM), collapse = "  ")
  }
  
  lines$options<-"[OPTIONS]"
  lines$options2<-paste(c(SumReport, AuxFiles, RExport), collapse = "  ")
  
  if (SetScale == TRUE) {
    lines$scale<-"[SCALE]"
    lines$scale2<-paste(ScaleFactor, collapse = "  ")
  }
  
  if (PercentileReport == TRUE) {
    lines$perc<-"[PERC]"
    lines$perc2<-paste(Percentile, collapse = "  ")
  }
  
  #return(lines)
  # Write the lines to a text file
  write.table(paste(lines,sep="\n"), file = file.path(output.dir, paste0(ModelName, ".inp")), row.names = FALSE, col.names = FALSE, sep = " ", quote = FALSE, append=FALSE)
  
}




